project:
  type: website
  output-dir: _site

website:
  title: "Pratyusha Sarkar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: research.qmd
      - href: publications.qmd
      - href: teaching.qmd
format:
  html:
    toc: true
