project:
  type: website
  output-dir: _site

website:
  title: "Pratyusha Sarkar"
  navbar:
   - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: CV

