project:
  type: website
  output-dir: _site

website:
  title: "Pratyusha Sarkar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - publications.qmd
      - teaching.qmd
format:
  html:
    toc: true
